### ISSUE TITLE
报告：源代码中有bug——607行

### ISSUE THREAD

**Issue by canjieChen** [findyou/HTMLTestRunnerCN#16]
报告：源代码中有bug——607行
有一种情况未覆盖，即执行的用例数为0，导致被除数为0报错
ZeroDivisionError: float division by zero
:octocat: 自己偷偷改了源码
改之前：
![image](https://user-images.githubusercontent.com/25762935/57194101-49b58380-6f75-11e9-9f80-15e254f35a15.png)

自己偷偷改了之后：
![image](https://user-images.githubusercontent.com/25762935/57194111-60f47100-6f75-11e9-8327-b682d122db2a.png)

**Comment by findyou** [comment]
找时间更新一下，thanks

**Comment by ingShen** [comment]
> 找时间更新一下，thanks

还是没改吗/doge
